const path = require('path');

module.exports = {
  packagerConfig: {
    name: 'Aerview',
    executableName: 'Aerview',
    extraResource: [
      path.join(__dirname, 'python-embed'),
      path.join(__dirname, 'backend-bundle'),
    ],
    ignore: [
      /^\/training/,
      /^\/src/,
      /^\/public/,
      /^\/backend$/,
      /^\/backend\//,
      /^\/backend-bundle$/,
      /^\/backend-bundle\//,
      /^\/backend-dist/,
      /^\/python-embed$/,
      /^\/python-embed\//,
      /^\/out/,
      /^\/release/,
      /^\/build/,
      /^\/dist/,
      /^\/scripts/,
      /^\/\.venv/,
      /^\/\.git/,
      /^\/\.gitignore/,
      /^\/\.env/,
      /^\/get-pip\.py/,
      /^\/hook-torch\.py/,
      /^\/README\.md/,
      /^\/tsconfig/,
      /^\/eslint/,
      /^\/vite\.config/,
      /^\/components\.json/,
      /^\/node_modules\/\.cache/,
      /\.spec$/,
      /\.zip$/,
      /setup_freeze\.py/,
    ],
    win32metadata: {
      CompanyName: 'Aerview',
      FileDescription: 'Aerview — Action Recognition',
      ProductName: 'Aerview',
    },
  },
  rebuildConfig: {},
  makers: [
    {
      name: '@electron-forge/maker-squirrel',
      platforms: ['win32'],
      config: {
        name: 'Aerview',
        setupExe: 'AerviewSetup.exe',
        authors: 'Aerview',
        description: 'Action Recognition Application',
      },
    },
    {
      name: '@electron-forge/maker-zip',
      platforms: ['win32'],
    },
  ],
};